---

- hosts: localhost
  tasks:
    - name: Add nginx apt repository
      apt_repository: repo="ppa:nginx/stable" state=present

    - name: Install nginx
      apt: name=nginx state=latest update_cache=yes

    - name: Install unzip
      apt: name=unzip state=present

    - name: Copy nginx config
      copy: src=default dest=/etc/nginx/sites-available/default

    - name: Remove default index.html
      file: path={{ item }} state=absent
      with_fileglob:
        - /var/www/html/*.html

    - name: Reload nginx
      service: name=nginx state=reloaded

    - name: Unpack archives
      unarchive: src={{ item }} dest=/var/www/html
      with_fileglob:
        - /vagrant/*.zip

    - debug: msg="http{{ ":" }}//{{ ansible_default_ipv4.address }}/"
